module.exports.getStaticClubData = () => {
        return [
            { "division": "A", "area": "11", "clubName": "Hudson River Toastmasters (8558)" },
            { "division": "A", "area": "11", "clubName": "IBM Westchester Toastmasters (648356)" },
            { "division": "A", "area": "11", "clubName": "Peekskill Toastmasters (3171395)" },
            { "division": "A", "area": "11", "clubName": "Northern Westchester Toastmasters (3797112)" },
            { "division": "A", "area": "12", "clubName": "BASF Tarrytown Toastmasters (3638279)" },
            { "division": "A", "area": "12", "clubName": "Regeneron Toastmasters (5829986)" },
            { "division": "A", "area": "12", "clubName": "WSP-BCM Toastmasters (7176388)" },
            { "division": "A", "area": "13", "clubName": "Westchester Toastmasters (863)" },
            { "division": "A", "area": "13", "clubName": "Speakers With Authority (5463)" },
            { "division": "A", "area": "13", "clubName": "United We Stand Toastmasters Club (9938)" },
            { "division": "A", "area": "13", "clubName": "Westchester Advanced Club (695803)" },
            { "division": "A", "area": "14", "clubName": "Cross Westchester Toastmasters (9976)" },
            { "division": "A", "area": "14", "clubName": "PepsiCo Valhalla Toastmasters Club (828089)" },
            { "division": "A", "area": "14", "clubName": "Legends For Life! (889516)" },
            { "division": "A", "area": "15", "clubName": "Pepsico Toastmasters Club (7230)" },
            { "division": "A", "area": "15", "clubName": "Swiss Toast Club (716600)" },
            { "division": "A", "area": "15", "clubName": "Priceless Speakers (1199057)" },
            { "division": "A", "area": "15", "clubName": "The Toast of Purchase (5864849)" },
            { "division": "B", "area": "21", "clubName": "La Voz Latina Toastmasters (1488421)" },
            { "division": "B", "area": "21", "clubName": "Monroe College Toastmasters (2218018)" },
            { "division": "B", "area": "21", "clubName": "Bronx Advanced Speakers (3337790)" },
            { "division": "B", "area": "21", "clubName": "Mount Vernon Toast (5341900)" },
            { "division": "B", "area": "22", "clubName": "Toast Of The Bronx Club (3035)" },
            { "division": "B", "area": "22", "clubName": "Co-op City Toastmasters Club (3824)" },
            { "division": "B", "area": "22", "clubName": "Einstein Toastmasters (1500422)" },
            { "division": "B", "area": "23", "clubName": "Bronx Toastmasters Club (6615)" },
            { "division": "B", "area": "23", "clubName": "MI Toastmasters (1322088)" },
            { "division": "B", "area": "23", "clubName": "Consumer Reports Toastmasters (3640336)" },
            { "division": "B", "area": "23", "clubName": "MIT Toastmasters (6576008)" },
            { "division": "B", "area": "24", "clubName": "TIC Toastmasters Club (2676)" },
            { "division": "B", "area": "24", "clubName": "Harlem Toastmasters (8594)" },
            { "division": "B", "area": "24", "clubName": "TORCH Toastmasters (1168440)" },
            { "division": "B", "area": "24", "clubName": "Columbia University Toastmasters  (3890961)" },
            { "division": "B", "area": "25", "clubName": "Douglas Elliman /west Side Toasties (595443)" },
            { "division": "B", "area": "25", "clubName": "West Side Talkers (1180341)" },
            { "division": "B", "area": "25", "clubName": "Fordham Lincoln Center (4776065)" },
            { "division": "B", "area": "25", "clubName": "DE Squared (5580612)" },
            { "division": "C", "area": "31", "clubName": "Pacers Toastmasters Club (2608)" },
            { "division": "C", "area": "31", "clubName": "AB Toastmasters (1588600)" },
            { "division": "C", "area": "31", "clubName": "Macquarie New York (7291924)" },
            { "division": "C", "area": "32", "clubName": "Ringers Toastmasters Club (7890)" },
            { "division": "C", "area": "32", "clubName": "Excellent Toastmasters (1410471)" },
            { "division": "C", "area": "32", "clubName": "BNP Paribas Toastmasters (3332242)" },
            { "division": "C", "area": "32", "clubName": "French/Bilingual Toastmasters of NY (7315453)" },
            { "division": "C", "area": "33", "clubName": "Leadership Roundtable  (1636)" },
            { "division": "C", "area": "33", "clubName": "Bryant Park Toastmasters Club (2895)" },
            { "division": "C", "area": "33", "clubName": "CFA NY Toastmasters (965817)" },
            { "division": "C", "area": "33", "clubName": "Barclays New York Toastmasters (5418945)" },
            { "division": "C", "area": "34", "clubName": "SEC Roughriders Club (1876)" },
            { "division": "C", "area": "34", "clubName": "Traffic Club (2286)" },
            { "division": "C", "area": "34", "clubName": "Mazars USA LLP (1166775)" },
            { "division": "C", "area": "34", "clubName": "Marsh McLennan Companies NY (2078496)" },
            { "division": "C", "area": "35", "clubName": "Deloitte Tri-State Toastmasters  (1244840)" },
            { "division": "C", "area": "35", "clubName": "Midtown's Best @ Morgan Stanley (1700500)" },
            { "division": "C", "area": "35", "clubName": "The Big Toast NYC (7419138)" },
            { "division": "C", "area": "36", "clubName": "BlackRock Speaks NY (2884725)" },
            { "division": "C", "area": "36", "clubName": "The World's Leading Toastmasters (4315364)" },
            { "division": "C", "area": "36", "clubName": "Speak Up Swiss Re (6547516)" },
            { "division": "C", "area": "36", "clubName": "Dewan Shai (7376563)" },
            { "division": "D", "area": "41", "clubName": "Knickerbocker Toastmasters Club (137)" },
            { "division": "D", "area": "41", "clubName": "Roosevelt Island Club (4121)" },
            { "division": "D", "area": "41", "clubName": "East Side Toastmasters Club (6138)" },
            { "division": "D", "area": "41", "clubName": "Yorkville Evening Stars - YES (5425506)" },
            { "division": "D", "area": "41", "clubName": "New York Storytellers (6606660)" },
            { "division": "D", "area": "42", "clubName": "Humorous Toastmasters (1296797)" },
            { "division": "D", "area": "42", "clubName": "730 Toastmasters (1387307)" },
            { "division": "D", "area": "42", "clubName": "Bloomberg New York Toastmasters (3618250)" },
            { "division": "D", "area": "42", "clubName": "Gotham Speakers Toastmasters Club (3966637)" },
            { "division": "D", "area": "42", "clubName": "Geller and Company (7708987)" },
            { "division": "D", "area": "43", "clubName": "JPMorgan Toastmasters NYC (3793452)" },
            { "division": "D", "area": "43", "clubName": "KPMG NYO Toastmasters Club (4405755)" },
            { "division": "D", "area": "43", "clubName": "Wafra Toastmasters (6931829)" },
            { "division": "D", "area": "43", "clubName": "TD NYC Toastmasters Club (7702911)" },
            { "division": "D", "area": "44", "clubName": "Mount Sinai Toastmasters (1023495)" },
            { "division": "D", "area": "44", "clubName": "Metnyc (1213823)" },
            { "division": "D", "area": "44", "clubName": "Stagecoach Speakers, NYC (4748139)" },
            { "division": "D", "area": "44", "clubName": "Societe Generale Toastmasters, USA (6765848)" },
            { "division": "D", "area": "45", "clubName": "Nichibei Toastmasters Club (6394)" },
            { "division": "D", "area": "45", "clubName": "World Voices Club (643436)" },
            { "division": "D", "area": "45", "clubName": "Advanced Debaters (3313240)" },
            { "division": "D", "area": "45", "clubName": "Persuasive Toastmasters (4634928)" },
            { "division": "D", "area": "45", "clubName": "Toastmasters Int'l Club - Elsevier NYC (6660424)" },
            { "division": "D", "area": "46", "clubName": "Global Expression Club (5596)" },
            { "division": "D", "area": "46", "clubName": "Pfree Speech Toastmasters Club (7883)" },
            { "division": "D", "area": "46", "clubName": "Travelers NYC (3433011)" },
            { "division": "D", "area": "46", "clubName": "A+E Networks NYC (6501985)" },
            { "division": "D", "area": "46", "clubName": "Speaking Easy (7560123)" },
            { "division": "E", "area": "51", "clubName": "Times Toastmasters (1548645)" },
            { "division": "E", "area": "51", "clubName": "Legg Mason Toastmasters - NY Chapter (5821058)" },
            { "division": "E", "area": "52", "clubName": "EY NYC Toastmasters (2560548)" },
            { "division": "E", "area": "52", "clubName": "Toastmasters NYC Microsoft (6021925)" },
            { "division": "E", "area": "53", "clubName": "Greenspeakers Club (3172)" },
            { "division": "E", "area": "53", "clubName": "NYC Equitable Toastmasters Club (3507)" },
            { "division": "E", "area": "53", "clubName": "Amazon NYC Toastmasters Club (7226903)" },
            { "division": "E", "area": "54", "clubName": "Vanderbilt Club (3061)" },
            { "division": "E", "area": "54", "clubName": "Lexington Toastmasters (1254058)" },
            { "division": "E", "area": "54", "clubName": "Jade Toastmasters Club (1721565)" },
            { "division": "E", "area": "54", "clubName": "Midtown Masters (4672690)" },
            { "division": "E", "area": "55", "clubName": "Extraordinary Talkers (735)" },
            { "division": "E", "area": "55", "clubName": "FactMasters (1526129)" },
            { "division": "E", "area": "55", "clubName": "Toastmasters @ MSK (1551020)" },
            { "division": "E", "area": "56", "clubName": "Metro New York (451)" },
            { "division": "E", "area": "56", "clubName": "Graybar Club (1436)" },
            { "division": "E", "area": "56", "clubName": "New York Toastmasters Club (1949)" },
            { "division": "E", "area": "56", "clubName": "Girl Scouts of the USA (7202219)" },
            { "division": "C", "area": "36", "clubName": "Alvarez & Marsal Taxand (077800702)" },
            { "division": "D", "area": "43", "clubName": "Wafra Toastmasters (6931829)" },
            { "division": "E", "area": "51", "clubName": "Acuris New York Toastmasters (7580325)" },
            { "division": "E", "area": "51", "clubName": "The Durst Organization Employees NYC (6732803)" },
            { "division": "E", "area": "52", "clubName": "NY WAM-OI Toastmasters (7450958)" },
            { "division": "E", "area": "52", "clubName": "Chubb NYC Toastmasters Club (77665933)" },
        ];
    };